subjects=["Maths","Science","Tamil","ICT","English"]
print(subjects)
print(type(subjects))
print(subjects[0])
print(subjects[-1])
print(len(subjects))
subjects[0]="History"
print(subjects)
subjects.append("Physics")
print(subjects)